### ISSUE TITLE
 java.lang.NoSuchFieldError: No field applicationContext: Android

### ISSUE THREAD

**Issue by ajitdubey-mob-ibtech** [twilio/sync-quickstart-android#16]
Hi Team,

I have integrated the Android Twilio Sync Client in a demo project.

**Problem**: I am not able to create a sync client.

**Android Min SDK**: 21
**Android Max SDK**: 33
**Kotlin Version**: 1.7.10

**Twilio Sync Plugin:**
`implementation "com.twilio:sync-android:3.0.0"`

**Crash occurs while creating the client.**

```
` SyncClient.create(applicationContext, accessToken, SyncClient.Properties.defaultProperties()) { client ->
            syncClient = client
            syncClient?.setListener(object : SyncClient.SyncClientListener {
                override fun onConnectionStateChanged(newState: SyncClient.ConnectionState) {
                    Timber.d("Connection status: $newState")
                }
            })
        }`
```

**Exception:** 
 ```
 java.lang.NoSuchFieldError: No field applicationContext of type Landroid/content/Context; in class Lcom/twilio/util/ApplicationContextHolder; or its superclasses (declaration of 'com.twilio.util.ApplicationContextHolder' appears in /data/app/~~j4sfn_722vZJL4erCfoU8w==/xxx.xxx.com-O0MFt8OyerRtMJxFVbMD5Q==/base.apk!classes18.dex)
                 	at com.twilio.sync.SyncClientImpl.create(SyncClientImpl.java:56)
                 	at com.twilio.sync.SyncClient.create(SyncClient.java:35)
```

Please help me out to fix this issue.

**Comment by rusmonster** [comment]
Hello!
Please try to bump the kotlin version in your project to the latest `1.8.20`
Let me know if it helped

**Comment by ajitdubey-mob-ibtech** [comment]
@rusmonster  Thanks for the update.
I have updated Kotlin version 1.8.0. The latest android studio(Flamingo) supports the Kotlin stable version 1.8.0.

**Action**: Updated Kotlin version from  1.7.10 t 1.8.0
 kotlin_version = '1.8.0'

**Other Configuration:**

1.    compileSdkVersion 33
2.    minSdkVersion 21
3.   targetSdkVersion 33

**Result:**  Issue is the same.

**Log:** 
 java.lang.NoSuchFieldError: No field applicationContext of type Landroid/content/Context; in class Lcom/twilio/util/ApplicationContextHolder; or its superclasses (declaration of 'com.twilio.util.ApplicationContextHolder' appears in /data/app/~~Als0SRGENkfGGmf4c3eFSw==/com.xx.xxxx-7TzLVbY9OWKXLfHL7HuymQ==/base.apk!classes18.dex)
                 	at com.twilio.sync.SyncClientImpl.create(SyncClientImpl.java:56)
                 	at com.twilio.sync.SyncClient.create(SyncClient.java:35)
                 	at com.xxxx.xxxxx.view.base.BaseActivity.createSyncClient(BaseActivity.kt:268)

Please help me.

**Comment by rusmonster** [comment]
@ajitdubey-mob-ibtech 
I've just created a new empty project in Android Studio, added the `SyncClient.create` call and it works for me.
Try to download the project, check if it works for you and then compare dependencies versions with your project setup. Especially the gradle and the android gradle plugin versions.
[TmpSync.zip](https://github.com/twilio/sync-quickstart-android/files/11260340/TmpSync.zip)

PS: Put your token generator url into `MainActivity.kt:45`

**Comment by ajitdubey-mob-ibtech** [comment]
@rusmonster Yeah, in the demo project, it's working fine at my end too.

**Comment by rusmonster** [comment]
@ajitdubey-mob-ibtech Please let us know which difference (comparing to the default AS project) in your project setup cause this issue if/when you find it

**Comment by ajitdubey-mob-ibtech** [comment]
@rusmonster Sure,
 One thing I would request from the Twilio dev team instead of returning this kind of error it's better to tell us which plugin version you are using that is wrong please update it. I think that will be better for all developers.

**Comment by berkus** [comment]
@ajitdubey-mob-ibtech we don't control it, the error is returned not by us, but by Android runtime.

**Comment by ajitdubey-mob-ibtech** [comment]
@rusmonster In the new project I am able to create the Twilio sync client but We can't use it in the new project. 
In the existing project, we are using Twilio Voice, conversation SDK and a lot of third-party libraries. So, In the existing project, I need to integrate the Twilio sync SDK. 
The existing project is created 2 years back with old-way Gradle dependencies only this is the difference with the new project  but all the versions are updated.


@berkus I am sharing the whole log again with you Guyz if you can help us that would be grateful.

**Crash occurs at this line:**
 ```
 SyncClient.create(
                applicationContext, accessToken, SyncClient.Properties.defaultProperties(),
```

**Log:**

```
 FATAL EXCEPTION: main
                 Process: com.xxx.app, PID: 1716
                 java.lang.NoSuchFieldError: No field applicationContext of type Landroid/content/Context; in class Lcom/twilio/util/ApplicationContextHolder; or its superclasses (declaration of 'com.twilio.util.ApplicationContextHolder' appears in /data/app/~~WRBW0wsJnAQz9XCz12nd8Q==/com.xxx.app-IPHRyBsrU2Y8NactKti1IQ==/base.apk!classes18.dex)
                 	at com.twilio.sync.SyncClientImpl.create(SyncClientImpl.java:56)
                 	at com.twilio.sync.SyncClient.create(SyncClient.java:35)
                 	at com.xxx.app.view.base.BaseActivity.createSyncClient(BaseActivity.kt:269)
                 	at com.xxx.app.view.base.BaseActivity.access$createSyncClient(BaseActivity.kt:75)
                 	at com.xxx.app.view.base.BaseActivity$getTwilioSyncAccessToken$1$1.invoke(BaseActivity.kt:256)
                 	at com.xxx.app.view.base.BaseActivity$getTwilioSyncAccessToken$1$1.invoke(BaseActivity.kt:255)
                 	at com.xxx.app.view.base.BaseActivity$getTwilioSyncAccessToken$1.invokeSuspend$lambda$0(BaseActivity.kt:255)
                 	at com.xxx.app.view.base.BaseActivity$getTwilioSyncAccessToken$1.$r8$lambda$XQclJQ2BOTXbr156y6kVK1wHVyY(Unknown Source:0)
                 	at com.xxx.app.view.base.BaseActivity$getTwilioSyncAccessToken$1$$ExternalSyntheticLambda0.onChanged(Unknown Source:2)
                 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
                 	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
                 	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
                 	at androidx.lifecycle.LiveData.observe(LiveData.java:205)
                 	at com.xxx.app.view.base.BaseActivity$getTwilioSyncAccessToken$1.invokeSuspend(BaseActivity.kt:255)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at android.os.Handler.handleCallback(Handler.java:942)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:226)
                 	at android.os.Looper.loop(Looper.java:313)
                 	at android.app.ActivityThread.main(ActivityThread.java:8741)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f89fc7e, Dispatchers.Main.immediate]
```

**Comment by rusmonster** [comment]
@ajitdubey-mob-ibtech Can you post your both app and the root build.gradle with all dependencies?

**Comment by rusmonster** [comment]
@ajitdubey-mob-ibtech Also do you use the latest version `v5.1.0` of the ConversationsSDK in your project?

**Comment by rusmonster** [comment]
It looks I've reproduced the issue. The crash happens if you have both dependencies: `conversations-android:5.1.0` and `sync-android:3.0.0` in the same app. We will fix it and update the sync SDK asap, meanwhile as a workaround I can recommend to temporary downgrade to `conversations-android:5.0.0`.

@ajitdubey-mob-ibtech does it work for you?

**Comment by ajitdubey-mob-ibtech** [comment]
@rusmonster Yeah, I am using the latest version of conversation SDK.
` twilio_conversation_sdk= '5.1.0'`

**Comment by ajitdubey-mob-ibtech** [comment]
> @ajitdubey-mob-ibtech Also do you use the latest version `v5.1.0` of the ConversationsSDK in your project?

@rusmonster Yeah, I am using the latest version of conversation SDK.
 twilio_conversation_sdk= '5.1.0'

**Comment by ajitdubey-mob-ibtech** [comment]
> It looks I've reproduced the issue. The crash happens if you have both dependencies: `conversations-android:5.1.0` and `sync-android:3.0.0` in the same app. We will fix it and update the sync SDK asap, meanwhile as a workaround I can recommend to temporary downgrade to `conversations-android:5.0.0`.
> 
> @ajitdubey-mob-ibtech does it work for you?

I will try and let you know.

**Comment by ajitdubey-mob-ibtech** [comment]
> > It looks I've reproduced the issue. The crash happens if you have both dependencies: `conversations-android:5.1.0` and `sync-android:3.0.0` in the same app. We will fix it and update the sync SDK asap, meanwhile as a workaround I can recommend to temporary downgrade to `conversations-android:5.0.0`.
> > @ajitdubey-mob-ibtech does it work for you?
> 
> I will try and let you know.

@rusmonster thanks. Yeah, it's working with `conversations-android:5.0.0`.

**Comment by rusmonster** [comment]
The issue is fixed: The latest
```
conversations-android:5.1.1
sync-android:3.0.1
```
work fine in the same app
